### ISSUE TITLE
访问问题....

### ISSUE THREAD

**Issue by blueiou** [zhisheng17/blog#1]
亲....从该地址打包下载好，放到tomcat容器无法访问，显示要怎么解决呀~~ 咋办呀 T.T

**Comment by zhisheng17** [comment]
这只是代码，你打包放到tomcat去，当然没用的啊，需要你自己重新编译打war包，再放到tomcat去！

**Comment by blueiou** [comment]
是在我本地重新打的war包，放到Tomcat那里的了

**Comment by ssdmtank** [comment]
Missing artifact org.springframework.boot:spring-boot:jar:1.5.1.RELEASE
maven这个错什么原因

**Comment by zhisheng17** [comment]
@ssdmtank 缺少 sb 的jar 包
