### ISSUE TITLE
后台添加页面功能存在bug

### ISSUE THREAD

**Issue by Mrhs121** [zhisheng17/blog#13]
PageController中这段代码存在问题，你的添加页面所提交的参数没有allowComment以及allowPing，造成这里if直接跳过，那么你的Boolen对象就为空了

        if (null != allowComment) {  

            contents.setAllowComment(allowComment == 1);  

        }  

        if (null != allowPing) {  

            contents.setAllowPing(allowPing == 1);  

        }  

最后导致在IndexController处理自定义页面（page）的时候空指针异常，无法正常显示自定的页面

@GetMapping(value = "/{pagename}")  

    public String page(@PathVariable String pagename, HttpServletRequest request) {  

        ContentVo contents = contentService.getContents(pagename);  

        if (null == contents) {  

            System.out.println("----- aboutme is null");  

            return this.render_404();  

        }  

         // 这里出现了空指针异常  

        if (contents.getAllowComment()) {    

            String cp = request.getParameter("cp");  

            if (StringUtils.isBlank(cp)) {

                cp = "1";

            }

**建议将if直接去掉，直接contents.setAllowComment(true);**

**Comment by zhisheng17** [comment]
THX

**Comment by zhisheng17** [comment]
@Mrhs121 thx
