### ISSUE TITLE
关于设置密码的md5算法

### ISSUE THREAD

**Issue by beausefulman** [zhisheng17/blog#18]
user表里的账户admin的密码a66abb5684c45962d887564f08346e8d用md5解密后是admin123456，登录，报错，通过控制台发现密码admin123456经过加密后存到数据表的字符串是202cc9b0383b17524dc1086113e42c55。请问这是我的环境的原因还是开发者先后采用了不同加密算法？

**Comment by HaoChunYang** [comment]
密码是123456吧

**Comment by zhisheng17** [comment]
可以看下加密算法，然后自己在数据库修改下用户和加密后的密码
