### ISSUE TITLE
admin/login页面登陆404

### ISSUE THREAD

**Issue by Chasel-Shao** [zhisheng17/blog#2]
admin/login输入用户名和密码后，没响应

**Comment by zhisheng17** [comment]
数据库配置好了没?

**Comment by Chasel-Shao** [comment]
后端登陆接口有问题，改了一下

**Comment by suyu2015** [comment]
部署到主机的时候,上传文件报错,有遇到过吗?

**Comment by zhisheng17** [comment]
可以把报错信息贴出来，没遇到过 @suyu2015

**Comment by suyu2015** [comment]
@zhisheng17 
起初我以为是内存小了，调大配置了还是一样的，只是上传文件报错，其余功能都正常,本地上传也正常，就是主机上上传有点问题
11-Jan-2018 10:49:07.994 WARNING [www.noyang.com-startStop-1] org.apache.catalina.loader.WebappClassLoaderBase.clearReferencesJdbc The web application [ROOT] registered the JDBC driver [com.alibaba.druid.proxy.DruidDriver] but failed to unregister it when the web application was stopped. To prevent a memory leak, the JDBC Driver has been forcibly unregistered.
11-Jan-2018 10:49:07.994 WARNING [www.noyang.com-startStop-1] org.apache.catalina.loader.WebappClassLoaderBase.clearReferencesJdbc The web application [ROOT] registered the JDBC driver [com.mysql.jdbc.Driver] but failed to unregister it when the web application was stopped. To prevent a memory leak, the JDBC Driver has been forcibly unregistered.
11-Jan-2018 10:49:07.996 WARNING [www.noyang.com-startStop-1] org.apache.catalina.loader.WebappClassLoaderBase.clearReferencesThreads The web application [ROOT] appears to have started a thread named [net.sf.ehcache.CacheManager@28cf60e2] but has failed to stop it. This is very likely to create a memory leak. Stack trace of thread:
 java.lang.Object.wait(Native Method)
 java.lang.Object.wait(Object.java:502)
 java.util.TimerThread.mainLoop(Timer.java:526)
 java.util.TimerThread.run(Timer.java:505)
11-Jan-2018 10:49:07.996 WARNING [www.noyang.com-startStop-1] org.apache.catalina.loader.WebappClassLoaderBase.clearReferencesThreads The web application [ROOT] appears to have started a thread named [metadata.data] but has failed to stop it. This is very likely to create a memory leak. Stack trace of thread:
 sun.misc.Unsafe.park(Native Method)
 java.util.concurrent.locks.LockSupport.parkNanos(LockSupport.java:215)
 java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.awaitNanos(AbstractQueuedSynchronizer.java:2078)
 java.util.concurrent.ScheduledThreadPoolExecutor$DelayedWorkQueue.take(ScheduledThreadPoolExecutor.java:1093)
 java.util.concurrent.ScheduledThreadPoolExecutor$DelayedWorkQueue.take(ScheduledThreadPoolExecutor.java:809)
 java.util.concurrent.ThreadPoolExecutor.getTask(ThreadPoolExecutor.java:1074)
 java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1134)
 java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
 java.lang.Thread.run(Thread.java:748)

**Comment by plusleft** [comment]
@Chasel-Shao 登录成功问题解决了吗？我也遇到了类似问题，总是提示账号密码错误，找不到对的账号了。小白很慌求指教
