### ISSUE TITLE
html跳转全部是绝对路径。。。服了  例如/logout

### ISSUE THREAD

**Issue by boynton89** [zhisheng17/blog#25]

**Comment by webhx** [comment]
你是谁啊？我真的是一脸懵逼




------------------ 原始邮件 ------------------
发件人: "boynton89"<notifications@github.com>;
发送时间: 2019年9月6日(星期五) 中午11:42
收件人: "zhisheng17/blog"<blog@noreply.github.com>;
抄送: "Subscribed"<subscribed@noreply.github.com>;
主题: [zhisheng17/blog] html跳转全部是绝对路径。。。服了  例如/logout (#25)

**Comment by boynton89** [comment]
我需要把它作为子项目访问，必须带项目名的。

这里全部设置成了绝对路径，无法作为子项目使用。

**Comment by webhx** [comment]
你谁啊，哪个项目，能不能说清楚




------------------ 原始邮件 ------------------
发件人: "boynton89"<notifications@github.com>;
发送时间: 2019年9月6日(星期五) 中午11:43
收件人: "zhisheng17/blog"<blog@noreply.github.com>;
抄送: "倾国倾城"<1463309084@qq.com>;"Comment"<comment@noreply.github.com>;
主题: Re: [zhisheng17/blog] html跳转全部是绝对路径。。。服了  例如/logout (#25)




我需要把它作为子项目访问，必须带项目名的。
 
这里全部设置成了绝对路径，无法作为子项目使用。

**Comment by boynton89** [comment]
抱歉哈哈，我是在github上留言的，https://github.com/zhisheng17/blog这个项目

**Comment by boynton89** [comment]
我看了下 只有几处是绝对路径  我改一下就好了····

**Comment by zhisheng17** [comment]
好的，自己做下修改
