### ISSUE TITLE
后台任意账号登录

### ISSUE THREAD

**Issue by thiscodecc** [zhisheng17/blog#26]
登录后台,有一个记住我选项
<img width="520" alt="t1" src="https://user-images.githubusercontent.com/55778895/66936211-e4130a80-f06f-11e9-8d5c-ead5996af740.png">
选中此项选项后,后台会生成一个cookie,具体代码位置
**com.my.blog.website.controller.admin.AuthController 71行**
<img width="650" alt="t2" src="https://user-images.githubusercontent.com/55778895/66936380-2e948700-f070-11e9-852a-ba7aa3a66405.png">

<img width="587" alt="t3" src="https://user-images.githubusercontent.com/55778895/66936517-68658d80-f070-11e9-9682-bc45498d5a9f.png">
把这个登录用户的uid和WebConst.AES_SALT的值一起加密生成一个AES后的值,问题是这个WebConst.AES_SALT是在代码里被写死的啊.
<img width="541" alt="t4" src="https://user-images.githubusercontent.com/55778895/66936730-c5614380-f070-11e9-920a-b5d194665ca2.png">
只需要调用Tools.enAes方法,把第一个参数设置成uid的值.
<img width="931" alt="t5" src="https://user-images.githubusercontent.com/55778895/66937368-e9715480-f071-11e9-987c-95ee6c445e95.png">
访问后台时带上这个cookie
就可以直接登录了,
S_L_ID=bE4dI4D/zfuGCE85YwXz5g==
<img width="584" alt="t7" src="https://user-images.githubusercontent.com/55778895/66937564-3e14cf80-f072-11e9-83b1-34ed7a30dcc7.png">

<img width="834" alt="t6" src="https://user-images.githubusercontent.com/55778895/66937469-17569900-f072-11e9-92ba-d1040abc0d2b.png">

**Comment by ykl124** [comment]
请问一下楼上哥们，我是前端过来的，run CoreApplication的时候遇到一个问题，就是一直报错连不上本地数据库，具体报错：ERROR com.alibaba.druid.pool.DruidDataSource - init datasource error, url: jdbc:mysql://localhost:3306/tale?useSSL=false&useUnicode=true&characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull&autoReconnect=true
但是我本地的确已经把mysql启动起来了，端口也是3306没毛病，我都进到mysql服务里了，为什么还会报这个错呢

**Comment by ykl124** [comment]
> 登录后台,有一个记住我选项
> <img alt="t1" width="520" src="https://user-images.githubusercontent.com/55778895/66936211-e4130a80-f06f-11e9-8d5c-ead5996af740.png">
> 选中此项选项后,后台会生成一个cookie,具体代码位置
> **com.my.blog.website.controller.admin.AuthController 71行**
> <img alt="t2" width="650" src="https://user-images.githubusercontent.com/55778895/66936380-2e948700-f070-11e9-852a-ba7aa3a66405.png">
> 
> <img alt="t3" width="587" src="https://user-images.githubusercontent.com/55778895/66936517-68658d80-f070-11e9-9682-bc45498d5a9f.png">
> 
> 把这个登录用户的uid和WebConst.AES_SALT的值一起加密生成一个AES后的值,问题是这个WebConst.AES_SALT是在代码里被写死的啊.
> <img alt="t4" width="541" src="https://user-images.githubusercontent.com/55778895/66936730-c5614380-f070-11e9-920a-b5d194665ca2.png">
> 
> 只需要调用Tools.enAes方法,把第一个参数设置成uid的值.
> <img alt="t5" width="931" src="https://user-images.githubusercontent.com/55778895/66937368-e9715480-f071-11e9-987c-95ee6c445e95.png">
> 
> 访问后台时带上这个cookie 就可以直接登录了, S_L_ID=bE4dI4D/zfuGCE85YwXz5g==
> <img alt="t7" width="584" src="https://user-images.githubusercontent.com/55778895/66937564-3e14cf80-f072-11e9-83b1-34ed7a30dcc7.png">
> 
> <img alt="t6" width="834" src="https://user-images.githubusercontent.com/55778895/66937469-17569900-f072-11e9-92ba-d1040abc0d2b.png">

请问一下楼上哥们，我是前端过来的，run CoreApplication的时候遇到一个问题，就是一直报错连不上本地数据库，具体报错：ERROR com.alibaba.druid.pool.DruidDataSource - init datasource error, url: jdbc:mysql://localhost:3306/tale?useSSL=false&useUnicode=true&characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull&autoReconnect=true
但是我本地的确已经把mysql启动起来了，端口也是3306没毛病，我都进到mysql服务里了，为什么还会报这个错呢

**Comment by macleo** [comment]
发现重大bug了，
