### ISSUE TITLE
问一下后台账户和密码

### ISSUE THREAD

**Issue by pengcwl** [zhisheng17/blog#30]
多谢博主....

**Comment by macleo** [comment]
username:admin
password:123456 
多动手查，多看，多找
如果密码不对，就是：admin123456,自己试着看吧

**Comment by xxp1263020813** [comment]
鬼知道密码是什么，用数据库的密码都是错的

**Comment by xxp1263020813** [comment]
数据库的admin密码显示的不是123456,是因为加密了吗？

**Comment by macleo** [comment]
> 数据库的admin密码显示的不是123456,是因为加密了吗？

username:admin
password:123456

**Comment by dingxinyuan** [comment]
源码的数据库是作者本地的&nbsp; &nbsp; 你自己需要本地安装一个数据库&nbsp; &nbsp;然后创建一个与数据库连接名相同的库名&nbsp; &nbsp;表在项目启动时会自动生成




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "macleo"<notifications@github.com&gt;; 
发送时间: 2020年5月3日(星期天) 下午4:31
收件人: "zhisheng17/blog"<blog@noreply.github.com&gt;; 
抄送: "Subscribed"<subscribed@noreply.github.com&gt;; 
主题: Re: [zhisheng17/blog] 问一下后台账户和密码 (#30)





  
数据库的admin密码显示的不是123456,是因为加密了吗？
  
username:admin
 password:123456
 
&mdash;

**Comment by dingxinyuan** [comment]
项目创建好了   管理台注册就行------------------ 原始邮件 ------------------
发件人: "macleo"<notifications@github.com>
发送时间: 2020年5月3日(星期天) 下午4:31
收件人: "zhisheng17/blog"<blog@noreply.github.com>;
抄送: "Subscribed"<subscribed@noreply.github.com>;
主题: Re: [zhisheng17/blog] 问一下后台账户和密码 (#30)




  
数据库的admin密码显示的不是123456,是因为加密了吗？
  
username:admin
 password:123456
 
&mdash;

**Comment by lmingde** [comment]
密码是 admin123456 
通过md5加密...
全项目没有找到密码....我看issue然后用md5计算值和sql文件中插入的password匹配核实才确认的.
