### ISSUE TITLE
拦截器会拦截静态文件，导致登录页面样式失效，登陆成功后跳转失效

### ISSUE THREAD

**Issue by Hlingoes** [zhisheng17/blog#4]
BaseInterceptor.java 初次登录验证时会拦截静态文件，第57-60行
if (uri.startsWith("/admin") && !uri.startsWith("/admin/login") && null == user) {
       response.sendRedirect(request.getContextPath() + "/admin/login");
       return false;
 }
静态文件地址和权限拦截地址一模一样，首次进入登录页面的时候，页面样式会缺失，引用文件报错。登录成功后，跳转地址错误。（截图上传失败，很好复现）

**Comment by JackstrawEscape** [comment]
麻烦问下，你的启动后访问没有问题么？

**Comment by Hlingoes** [comment]
直接启动是有问题的，我修改之后没问题了，具体可以到我fork的项目中去看：https://github.com/Hlingoes/blog

**Comment by zhisheng17** [comment]
谢谢修复的bug
